fix: ci errors (#423)
fix anchor errors

fix group 3 errors

fix anchor errors group 2

Update pnpm-lock.yaml

update checking account pnpm lock

remove biome

update pnpm lock anchor group 0

move pnpm install in anchor workflow

update anchor version in group 0

Revert "update anchor version to 0.31.1"

This reverts commit ca12179fd9d1aebc0d0c87ccc5d2a738f8f307d0.

update anchor version to 0.31.1

add type:module to anchor bankrun tests

add with json to bankrun tests

remove curly braces from bankrun tests

use import in bankrun tests

fix ts strip only error

add type: "module" to basic native example package.json

add type module to package.json

fix ts strip only error

fix token-2022 errors

fix biome

remove seahorse and steel github workflows

silence warnings in basics example

- use workspace deps
- use solana-system-interface
- use borsh::to_vec()
- use allow unexpected cfgs and depreciated

add allow unexpected cfgs and update deps in basic examples

fix fundraiser and transfer token bankrun tests

fix checking-account and favorites error

update anchor version in anchor workflow

add cfgs lint to compression and oracles anchor examples

add cfg lint to token examples

add lints.rust unexpected_cfgs to basic examples

update anchor version in pnpm.yaml

update anchor version and remove allow attributes

update pnpm version

diff --git a/.github/workflows/anchor.yml b/.github/workflows/anchor.yml
--- a/.github/workflows/anchor.yml
+++ b/.github/workflows/anchor.yml
@@ -106,7 +106,7 @@ jobs:
       - uses: actions/checkout@v4
       - uses: heyAyushh/setup-anchor@v0.31
         with:
-          anchor-version: 0.31.1
+          anchor-version: 0.32.1
           solana-cli-version: stable
       - name: Display Versions and Install pnpm
         run: |
@@ -126,19 +126,19 @@ jobs:
             echo "Building and Testing $project"
             cd "$project" || return 1
 
+            # Install dependencies first
+            if ! pnpm install --frozen-lockfile; then
+              echo "::error::pnpm install failed for $project"
+              echo "$project: pnpm install failed" >> $GITHUB_WORKSPACE/failed_projects.txt
+              cd - > /dev/null
+              return 1
+            fi
+
             # Run anchor build
             if ! anchor build; then
               echo "::error::anchor build failed for $project"
               echo "$project: anchor build failed" >> $GITHUB_WORKSPACE/failed_projects.txt
               rm -rf target
-              cd - > /dev/null
-              return 1
-            fi
-
-            # Install dependencies
-            if ! pnpm install --frozen-lockfile; then
-              echo "::error::pnpm install failed for $project"
-              echo "$project: pnpm install failed" >> $GITHUB_WORKSPACE/failed_projects.txt
               cd - > /dev/null
               return 1
             fi
